# Generated by Django 6.0.3 on 2026-03-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_mentor",
            field=models.BooleanField(default=False, verbose_name="Ментор"),
        ),
        migrations.AddField(
            model_name="user",
            name="raw_password",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Сырой пароль",
            ),
        ),
    ]
