# Generated by Django 6.0.3 on 2026-03-20 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_is_mentor_user_raw_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mentor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ментор",
            ),
        ),
    ]
